name: volumes-job
region: europe-west1
project: helmless
image: 'us-docker.pkg.dev/cloudrun/container/hello:latest'
volumes:
  config:
    mountPath: /etc/config
    secret:
      name: app-config
      items:
        - path: config.json
        - version: '2'
          path: config.v2.json
  cache:
    mountPath: /cache
    emptyDir:
      size: 512Mi
  data:
    mountPath: /data
    readOnly: true
    gcs:
      bucket: helmless-data
      mountOptions:
        file-mode: '0644'
        dir-mode: '0755'
        uid: '1000'
        gid: '1000'
