apiVersion: v2
name: google-cloudrun-common
description: A Helm chart library for common Google Cloud Run helpers and schemas.
type: library
version: 0.1.0
icon: https://helmless.io/assets/images/helmless.png
maintainers:
  - name: Michael Reichenbach (Silthus)
    email: me@silthus.net
    url: https://github.com/silthus
